module.exports = {
  BOOKING_SENT: "BOOKING_SENT",
  BOOKING_ACCEPTED: "BOOKING_ACCEPTED",
  BOOKING_REJECTED: "BOOKING_REJECTED",
  BOOKING_CANCELED: "BOOKING_CANCELED",
  BOOKING_COMPLETED: "BOOKING_COMPLETED",
};
